backend:
    name: github
    repo: bdkiran/datarise
  
media_folder: /static/assets
public_folder: "/"
  
collections:
    - name: definitions
      label: Definitions
      folder: "src/pages/markdown-pages/definitions"
      create: true
      fields:
        - { name: category, label: Category, default: 'definition', hint: 'Do not change'}
        - { name: slug, label: Slug, default: '/dictionary/', hint: 'Add the path ending'}
        - { name: date, label: Date, widget: date, format: 'YYYY-MM-DD' }
        - { name: title, label: Title }
        - { name: body, label: Body, widget: markdown }

    - name: features
      label: Feature
      folder: "src/pages/markdown-pages/features"
      create: true
      fields:
        - { name: category, label: Category, default: 'feature', hint: 'Do not change'}
        - { name: slug, label: Slug, default: '/features/', hint: 'Add the path ending'}
        - { name: date, label: Date, widget: date, format: 'YYYY-MM-DD' }
        - { name: title, label: Title }
        - { name: image, label: Image, widget: image, allow_multiple: false }
        - { name: body, label: Body, widget: markdown }